server:
  port: ${SERVER_PORT:9102}
spring:
  profiles:
    active: ${SPRING_PROFILE_ACTIVE:local}
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/dbrpe
    username: user
    password: password
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL82Dialect
  cloud:
    aws:
      stack:
        auto: false
      credentials:
        accessKey: accessKey
        secretKey: secretKey
      region:
        static: us-east-1
      sqs:
        endpoint: ${SQS_ENDPOINT:http://localhost:4566}
        queue:
          uri: ${SQS_QUEUE_URI:http://localhost:4566/000000000000/queue-card}
          name: queue-card
feign:
  client:
    config:
      card-service:
        url: ${CARDS_URL:http://localhost:9103/cards}
algorithm:
  secret: secret
